In [ ]:
from google.colab import files
files.upload()

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('Screen Time Data.csv')
df

In [ ]:
df.shape

(28, 12)

In [ ]:
row,col=df.shape

In [ ]:
row

28

In [ ]:
df.info()

Working with specfic columns

In [ ]:
df.columns

Index(['index', 'Date', 'Week Day', 'Total Screen Time ', 'Social Networking',
       'Reading and Reference', 'Other', 'Productivity', 'Health and Fitness',
       'Entertainment', 'Creativity', 'Yoga'],
      dtype='object')

In [ ]:
df['Total Screen Time ']

In [ ]:
df['Total Screen Time '].min()

52

In [ ]:
df['Total Screen Time '].max()

198

In [ ]:
df['Total Screen Time '].median() #used in neumerical data

111.0

In [ ]:
df['Total Screen Time '].mean() #used in neumerical data

113.25

In [ ]:
df['Week Day'].mode() #used in catarogical data

In [ ]:
#standard deviation
df['Total Screen Time '].std()

43.562322320164775

A quantile is a statistical term that refers to the division of a dataset into equal parts. Quantiles help you understand the distribution of data by breaking it into intervals where a specific percentage of the data falls below a given value.

In [ ]:
df['Total Screen Time '].quantile(.25)

83.5

In [ ]:
df['Total Screen Time '].sort_values(ascending=False)

In [ ]:
df.describe()

In [ ]:
df.head(2)

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0

In [ ]:
df.tail(4)

In [ ]:
df[2:5]

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0

Copy

In [ ]:
df_copy=df.copy()
df_copy

Update

In [ ]:
df['Total Screen Time '].sort_values(ascending=False,inplace=True)